name: Test

on:
  push:
    branches: [ master ]
    paths:
      - '**.kt'
      - '**.kts'
      - '**.proto'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.kt'
      - '**.kts'
      - '**.proto'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Format Check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintCheck
          gradle-version: 7.4.2

      - name: Test Check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          gradle-version: 7.4.2
